# Generated by Django 3.1.12 on 2025-11-03 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20251031_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Optional duration in minutes', null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence', models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=10)),
                ('reminder_minutes_before', models.PositiveIntegerField(default=15, help_text='Minutes before start to remind')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Study Schedule',
                'verbose_name_plural': 'Study Schedules',
                'ordering': ['scheduled_start'],
            },
        ),
    ]
